import { IProduct } from '@/models/Product';

export const sampleProducts: (IProduct & { _id: string })[] = [
  // iPhones
  {
    _id: 'i1',
    name: 'iPhone 15 Pro Max',
    description: 'The ultimate iPhone experience with Natural Titanium finish and A17 Pro chip.',
    price: 450000,
    originalPrice: 480000,
    category: 'iPhones',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1591337676887-a217a6970a8a?q=80&w=1000&auto=format&fit=crop'],
    stock: 10,
    featured: true,
    specs: { ram: '8GB', storage: '256GB', battery: '4441mAh', camera: '48MP Main', display: '6.7" OLED' },
    createdAt: new Date()
  },
  {
    _id: 'i2',
    name: 'iPhone 14 Pro',
    description: 'Powerful A16 Bionic chip with Dynamic Island and 48MP camera.',
    price: 380000,
    originalPrice: 400000,
    category: 'iPhones',
    condition: 'Used',
    images: ['https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?q=80&w=1000&auto=format&fit=crop'],
    stock: 5,
    featured: false,
    specs: { ram: '6GB', storage: '128GB', battery: '3200mAh', camera: '48MP Triple', display: '6.1" OLED' },
    createdAt: new Date()
  },
  // Samsung
  {
    _id: 's1',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'The peak of Android innovation with Galaxy AI and 200MP camera.',
    price: 380000,
    originalPrice: 410000,
    category: 'Samsung',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=1000&auto=format&fit=crop'],
    stock: 15,
    featured: true,
    specs: { ram: '12GB', storage: '512GB', battery: '5000mAh', camera: '200MP Quad', display: '6.8" AMOLED' },
    createdAt: new Date()
  },
  {
    _id: 's2',
    name: 'Samsung Galaxy A54 5G',
    description: 'Awesome camera, awesome screen, awesome battery life.',
    price: 115000,
    originalPrice: 125000,
    category: 'Samsung',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1678911820864-e2c567c655d7?q=80&w=1000&auto=format&fit=crop'],
    stock: 25,
    featured: false,
    specs: { ram: '8GB', storage: '128GB', battery: '5000mAh', camera: '50MP Triple', display: '6.4" 120Hz' },
    createdAt: new Date()
  },
  // Google
  {
    _id: 'g1',
    name: 'Google Pixel 8 Pro',
    description: 'The smartest Pixel yet with pure Android and incredible AI camera features.',
    price: 220000,
    originalPrice: 240000,
    category: 'Google',
    condition: 'Used',
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1000&auto=format&fit=crop'],
    stock: 5,
    featured: true,
    specs: { ram: '12GB', storage: '128GB', battery: '5050mAh', camera: '50MP Triple', display: '6.7" LTPO' },
    createdAt: new Date()
  },
  // OnePlus
  {
    _id: 'o1',
    name: 'OnePlus 12',
    description: 'Smooth Beyond Belief. The fastest charging flagship in the market.',
    price: 185000,
    originalPrice: 195000,
    category: 'OnePlus',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1612448331650-d44772ff5f79?q=80&w=1000&auto=format&fit=crop'],
    stock: 8,
    featured: false,
    specs: { ram: '16GB', storage: '512GB', battery: '5400mAh', camera: '50MP Hasselblad', display: '6.8" 2K' },
    createdAt: new Date()
  },
  // Xiaomi
  {
    _id: 'x1',
    name: 'Xiaomi 14 Pro',
    description: 'Leica Optics and Snapdragon 8 Gen 3 for the ultimate mobile photographer.',
    price: 165000,
    originalPrice: 175000,
    category: 'Xiaomi',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=1000&auto=format&fit=crop'],
    stock: 12,
    featured: false,
    specs: { ram: '12GB', storage: '256GB', battery: '4880mAh', camera: '50MP Leica', display: '6.7" AMOLED' },
    createdAt: new Date()
  },
  // Realme
  {
    _id: 'r1',
    name: 'Realme GT 5',
    description: 'Performance flagship with 240W ultra-fast charging capability.',
    price: 125000,
    originalPrice: 135000,
    category: 'Realme',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1621330396173-e41b1cafd17f?q=80&w=1000&auto=format&fit=crop'],
    stock: 20,
    featured: false,
    specs: { ram: '16GB', storage: '512GB', battery: '4600mAh', camera: '50MP Sony', display: '6.7" 144Hz' },
    createdAt: new Date()
  },
  // Vivo
  {
    _id: 'v1',
    name: 'Vivo X100 Pro',
    description: 'Zeiss imaging system integrated for cinematic mobile videography.',
    price: 155000,
    originalPrice: 165000,
    category: 'Vivo',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=1000&auto=format&fit=crop'],
    stock: 6,
    featured: false,
    specs: { ram: '12GB', storage: '256GB', battery: '5000mAh', camera: '50MP Zeiss', display: '6.78" OLED' },
    createdAt: new Date()
  },
  // Accessories
  {
    _id: 'acc1',
    name: 'MagSafe Silicone Case',
    description: 'Soft-touch silicone case with perfect alignment for wireless charging.',
    price: 4500,
    originalPrice: 6000,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1000&auto=format&fit=crop'],
    stock: 50,
    featured: true,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'acc2',
    name: 'Original 20W USB-C Adapter',
    description: 'Fast, efficient charging at home, in the office, or on the go.',
    price: 6500,
    originalPrice: 7500,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1583860814424-d0d47ee30251?q=80&w=1000&auto=format&fit=crop'],
    stock: 30,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  // Budget Accessories
  {
    _id: 'gp1',
    name: '9H Tempered Glass Protector',
    description: 'Edge-to-edge protection for your mobile screen.',
    price: 150,
    originalPrice: 250,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1606229365485-93a3b8ee0385?q=80&w=1000&auto=format&fit=crop'],
    stock: 100,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'gp2',
    name: 'Premium Matte Glass Protector',
    description: 'Anti-fingerprint matte finish for a smooth touch experience.',
    price: 250,
    originalPrice: 350,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1611186871348-b1ec696e5205?q=80&w=1000&auto=format&fit=crop'],
    stock: 80,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'gp3',
    name: 'Privacy Glass Protector',
    description: 'Keeps your screen contents private from side angles.',
    price: 350,
    originalPrice: 450,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1510557880182-3d4d3cba3f21?q=80&w=1000&auto=format&fit=crop'],
    stock: 60,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'gp4',
    name: 'Full Glue Curved Glass',
    description: 'Perfect fit for curved display flagships.',
    price: 450,
    originalPrice: 550,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1580910051074-3eb6948865c5?q=80&w=1000&auto=format&fit=crop'],
    stock: 40,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'gp5',
    name: 'Diamond Quality Screen Guard',
    description: 'Ultra-tough scratch resistance for extreme durability.',
    price: 550,
    originalPrice: 750,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1556656793-062ff9878273?q=80&w=1000&auto=format&fit=crop'],
    stock: 30,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'gp6',
    name: 'Anti-Blue Light Protector',
    description: 'Reduces eye strain by filtering harmful blue light.',
    price: 650,
    originalPrice: 850,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1546054454-aa26e2b734c7?q=80&w=1000&auto=format&fit=crop'],
    stock: 25,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'ep1',
    name: 'Basic Wired Earphones',
    description: 'Clear sound with built-in microphone for daily use.',
    price: 250,
    originalPrice: 350,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1000&auto=format&fit=crop'],
    stock: 120,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  },
  {
    _id: 'ep2',
    name: 'Hi-Fi Stereo Earbuds',
    description: 'Enhanced bass and tangle-free cable for music lovers.',
    price: 350,
    originalPrice: 500,
    category: 'Accessories',
    condition: 'New',
    images: ['https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?q=80&w=1000&auto=format&fit=crop'],
    stock: 100,
    featured: false,
    specs: { ram: '-', storage: '-', battery: '-', camera: '-', display: '-' },
    createdAt: new Date()
  }

];

